"use strict";
/**
 * Possible Problems
 * @link {https://zh-hans.eslint.org/docs/latest/rules/#possible-problems}
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    rules: {
        'array-callback-return': 'off',
        'constructor-super': 'error',
        'for-direction': 'off',
        'getter-return': 'error',
        'no-async-promise-executor': 'off',
        'no-await-in-loop': 'error',
        'no-class-assign': 'off',
        'no-compare-neg-zero': 'warn',
        'no-cond-assign': 'error',
        'no-const-assign': 'error',
        'no-constant-binary-expression': 'warn',
        'no-constant-condition': 'warn',
        'no-constructor-return': 'warn',
        'no-control-regex': 'off',
        'no-debugger': 'error',
        'no-dupe-args': 'error',
        'no-dupe-class-members': 'error',
        'no-dupe-else-if': 'error',
        'no-dupe-keys': 'error',
        'no-duplicate-case': 'error',
        'no-duplicate-imports': 'error',
        'no-empty-character-class': 'error',
        'no-empty-pattern': 'error',
        'no-ex-assign': 'error',
        'no-fallthrough': 'error',
        'no-func-assign': 'warn',
        'no-import-assign': 'error',
        'no-inner-declarations': 'off',
        'no-invalid-regexp': 'error',
        'no-irregular-whitespace': 'off',
        'no-loss-of-precision': 'error',
        'no-misleading-character-class': 'off',
        'no-new-native-nonconstructor': 'error',
        'no-new-symbol': 'error',
        'no-obj-calls': 'error',
        'no-promise-executor-return': 'warn',
        'no-prototype-builtins': 'warn',
        'no-self-assign': 'error',
        'no-self-compare': 'error',
        'no-setter-return': 'error',
        'no-sparse-arrays': 'off',
        'no-template-curly-in-string': 'error',
        'no-this-before-super': 'error',
        'no-undef': 'off',
        'no-unexpected-multiline': 'error',
        'no-unmodified-loop-condition': 'error',
        'no-unreachable': 'error',
        'no-unreachable-loop': 'error',
        'no-unsafe-finally': 'off',
        'no-unsafe-negation': 'off',
        'no-unsafe-optional-chaining': 'off',
        'no-unused-private-class-members': 'off',
        'no-unused-vars': 'error',
        'no-use-before-define': 'warn',
        'no-useless-backreference': 'off',
        'require-atomic-updates': 'warn',
        'use-isnan': 'error',
        'valid-typeof': 'error', // "Enforce comparing `typeof` expressions against valid strings"
    },
};
